# Generated by Django 5.1.7 on 2025-03-22 10:39

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='EventLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('serial_no', models.IntegerField()),
                ('version', models.IntegerField()),
                ('account_id', models.CharField(max_length=50)),
                ('instance_id', models.CharField(max_length=50)),
                ('src_addr', models.GenericIPAddressField()),
                ('dst_addr', models.GenericIPAddressField()),
                ('src_port', models.IntegerField()),
                ('dst_port', models.IntegerField()),
                ('protocol', models.IntegerField()),
                ('packets', models.IntegerField()),
                ('bytes', models.IntegerField()),
                ('start_time', models.BigIntegerField()),
                ('end_time', models.BigIntegerField()),
                ('action', models.CharField(max_length=10)),
                ('log_status', models.CharField(max_length=10)),
            ],
        ),
    ]
