# Generated by Django 5.1.7 on 2025-03-23 17:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('logs', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='eventlog',
            name='file_name',
            field=models.CharField(db_column='filename', max_length=255, null=True),
        ),
    ]
